Move files to ui/ and update README
GoogleCloudPlatform/dagify pull request #98
Opened 2024-10-17 15:16 UTC by shreyaprabhu-g

2024-10-18 08:22 UTC, KonradSchieban requested changes

2024-10-18 08:22 UTC, KonradSchieban commented on app.py
please move app.py into the ui folder as well.

2024-10-18 08:22 UTC, KonradSchieban commented on requirements.txt
please rebase to get the latest dependencies.

2024-10-20 14:31 UTC, shreyaprabhu-g commented on requirements.txt
updated

2024-10-21 08:32 UTC, KonradSchieban approved these changes
LGTM

2024-10-21 08:32 UTC, KonradSchieban commented
Thank you for working on the updates @shreyaprabhu-g ! 🥳

2024-10-21 08:33 UTC, merged